#!/usr/bin/env bash
#
# session-logger.sh — session black-box log + checkpoint counter
#
# Claude Code PostToolUse hook (matcher: Bash|Write|Edit). It does two things:
#   1. LOG: append every action (tool + command/file + timestamp) to
#      $MESH_SESSION_LOG_DIR/YYYYMMDD-<session>.md  (a black box, independent
#      of the running agent).
#   2. CHECKPOINT: every N actions, inject a checkpoint reminder via
#      additionalContext so the agent pauses and summarizes progress.
#
# Config (env):
#   MESH_CHECKPOINT_EVERY   (15)                       actions between checkpoints; 0 disables
#   MESH_SESSION_LOG_DIR    (~/.claude/session-logs)   where logs are written
#
# Requires: jq. Never fails the hook (always exit 0) — a hook that breaks is
# more annoying than the problem it solves.
#
# Install: add to .claude/settings.json under hooks.PostToolUse with
#          matcher "Bash|Write|Edit".

set +e  # never abort

EVERY="${MESH_CHECKPOINT_EVERY:-15}"
LOGDIR="${MESH_SESSION_LOG_DIR:-$HOME/.claude/session-logs}"
mkdir -p "$LOGDIR" 2>/dev/null

input=$(cat 2>/dev/null)

# Extract fields (fallback if jq fails or a field is missing)
sid=$(printf '%s' "$input" | jq -r '.session_id // "nosession"' 2>/dev/null); [ -z "$sid" ] && sid="nosession"
tool=$(printf '%s' "$input" | jq -r '.tool_name // "?"' 2>/dev/null); [ -z "$tool" ] && tool="?"

# Per-tool detail
case "$tool" in
  Bash)
    detail=$(printf '%s' "$input" | jq -r '.tool_input.command // ""' 2>/dev/null | tr '\n' ' ' | cut -c1-200)
    ;;
  Write|Edit)
    detail=$(printf '%s' "$input" | jq -r '.tool_input.file_path // ""' 2>/dev/null)
    ;;
  *)
    detail=""
    ;;
esac

sid_short=$(printf '%s' "$sid" | cut -c1-8)
day=$(date +%Y%m%d)
logfile="$LOGDIR/${day}-${sid_short}.md"
ts=$(date +%H:%M:%S)

# Write header if the log is new
if [ ! -f "$logfile" ]; then
  {
    echo "# Session log — ${day} (${sid_short})"
    echo ""
    echo "> Automatic black box. Records Bash/Write/Edit with timestamps. Generated by session-logger.sh."
    echo ""
  } >> "$logfile" 2>/dev/null
fi

# Append the action
printf -- '- `%s` **%s** %s\n' "$ts" "$tool" "$detail" >> "$logfile" 2>/dev/null

# Per-session counter
countfile="${TMPDIR:-/tmp}/mesh-checkpoint-${sid_short}"
count=$(cat "$countfile" 2>/dev/null); [ -z "$count" ] && count=0
count=$((count + 1))
printf '%s' "$count" > "$countfile" 2>/dev/null

# Every N actions → inject a checkpoint reminder
if [ "$EVERY" -gt 0 ] && [ $((count % EVERY)) -eq 0 ]; then
  ctx="CHECKPOINT (${count} actions executed). Pause and summarize in 3 lines: (1) what is done so far, (2) what you are doing now, (3) what remains. Full command log: ${logfile}. This counters loss of visibility in long sessions — do not skip it even mid-flow."
  # Emit JSON with additionalContext (injected into the model)
  jq -cn --arg c "$ctx" '{hookSpecificOutput:{hookEventName:"PostToolUse",additionalContext:$c}}' 2>/dev/null
fi

exit 0
